name: Print Hello World
on:
  push: 

jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: run function
        run: node ./test.js